
services:
  # Écran Frontend (Vos pages HTML/JS)
  frontend:
    build: ./Frontend  # Nom exact de votre dossier frontend
    ports:
      - "8080:80"       # Accès au site sur http://localhost:8080
    restart: always

  # Serveur Backend (Votre API Node.js)
  backend:
    build: ./Backend   # Nom exact de votre dossier backend
    ports:
      - "3000:3000"     # Accès à l'API sur http://localhost:3000
    restart: always
